### ISSUE TITLE
FR: Offer F-Droid repo with this app

### ISSUE THREAD

**Issue by m-rey** [johanw666/Signal-Android#21]
I was wondering whether this for could be added to a f-droid repository. If using the main f-droid repo is not an option, then maybe a separate f-droid repo could hosted and used to distribute this app. What do you think?

**Comment by johanw666** [comment]
AFAIK the main F-Droid repo is no option because the code uses non-open source libraries from Google. Further, in the past there have been Signal forks on F-Droid and that didn't go well with the official Signal authors.

Further not all functionality would work if F-Droid compiled the sources because the location picker uses an API key that is linked to the apk signing key.

That leaves open a separate repo but I'm not very much into F-Droid, I don't know if that is much extra work.

**Comment by kzshantonu** [comment]
I vote for an fdroid repo. It *shouldn't* take more than 15 mins https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

**Comment by johanw666** [comment]
This has several issues: I run windows 7 so I would need to install Cygwin for a server, but last time I tried Cygwin didn't want to install on my machine for some reason.

Also, when I put a Signal fork on F-Droid I would have to change the application name, package name and icon to prevent issues with the Signal team, which I prefer not to do.
