### ISSUE TITLE
SMS functionality

### ISSUE THREAD

**Issue by okow** [johanw666/Signal-Android#74]
Hello Johan,

sorry for opening a bug, but this seems to be the only catagory not redirecting to the original signal.

In the release notes of the upstream signal i read, they now start to (or already have done so) remove the sms functionality.
Will you keep the corresponding code or will you follow with removal?
If the later; what is / will be the last version of your fork with fully working sms-capabilities?

Thanks in advance.

Kind regards
Olaf

**Comment by johanw666** [comment]
As I said before, I probably go with Signal with this, as it is probably too much work to maintain sms functionality. And I could not even test it fully if I kept it because mms support has veen dropped by all carriers in my country years ago.

I don't know which version will be the last with sms support, that depends on Signal.
